apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  labels:
    app: dispatch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      nodeSelector:
        role: app

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: dispatch
            topologyKey: kubernetes.io/hostname
      initContainers:
       - name: wait-for-rabbitmq
         image: busybox:1.36
         command:
          - sh
          - -c
          - |
           echo "Waiting for RabbitMQ..."
           until nc -z rabbit-headless 5672 >/dev/null 2>&1; do
           echo "RabbitMQ not ready, retrying..."
           sleep 2
           done
           echo "RabbitMQ is ready!"

      containers:
        - name: dispatch
          image: robotshop/rs-dispatch:2.1.0
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_HOST
              value: rabbit-headless
---
apiVersion: v1
kind: Service
metadata:
  name: dispatch-service
spec:
  selector:
    app: dispatch
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082