resources:
  - persistantVolumeRabbit.yaml
  - persistantVolumeRabbitClaim.yaml
  - persistantVolumeRedis.yaml
  - persistantVolumeRedisClaim.yaml
  - rabbitHeadlessService.yaml
  - rabbitService.yaml
  - redisHeadlessService.yaml
  - redisService.yaml
  - statefulDeployRabbit.yaml
  - statefulDeployRedis.yaml
