apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      nodeSelector:
        role: app

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: ratings
            topologyKey: kubernetes.io/hostname
      initContainers:
       - name: wait-for-mysql
         image: busybox:1.36
         command:
          - sh
          - -c
          - |
           echo "Waiting for Mysql..."
           until nc -z mysql-headless 3306 >/dev/null 2>&1; do
             echo "Mygsql not ready, retrying..."
             sleep 2
           done
           echo "Mysql is ready!"

      containers:
        - name: ratings
          image: robotshop/rs-ratings:2.1.0
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: mysql-headless
---
apiVersion: v1
kind: Service
metadata:
  name: ratings-service
spec:
  selector:
    app: ratings
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30084