apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      nodeSelector:
        role: app
        affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: catalogue
            topologyKey: kubernetes.io/hostname
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Mongo..."
              until nc -z mongo-headless 27017 >/dev/null 2>&1; do
                echo "Mongo not ready, retrying..."
                sleep 2
              done
              echo "Mongo is ready!"
      containers:
        - name: catalogue
          image: robotshop/rs-catalogue:2.1.0
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_HOST
              value: mongo-headless
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    app: catalogue
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081