apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-dep
  labels:
    app: catalogue-dp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: catalogue-dp
  template:
    metadata:
      labels:
        app: catalogue-dp
    spec:
      nodeSelector:
        role: app

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: catalogue-dp
            topologyKey: kubernetes.io/hostname

      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Mongo..."
              until nc -z mongo-headless 27017 >/dev/null 2>&1; do
                echo "Mongo not ready, retrying..."
                sleep 2
              done
              echo "Mongo is ready!"

      containers:
        - name: catalogue
          image: robotshop/rs-catalogue:2.1.0
          ports:
            - containerPort: 8080
          env:
            - name: INSTANA_DISABLED
              value: "true"
            - name: MONGODB_HOST
              value: mongo-headless

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: catalogue-dp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
